### ISSUE TITLE
 InvalidRequestError: Request does not contain a host query parameter

### ISSUE THREAD

**Issue by NomanHameed** [Shopify/shopify-app-template-node#1234]
I'm creating a Shopify app using node with PostgreSQL my app working fine on local with Ngrok but when i deploy on Heroku on calling app with shop it returns error.

[shopify-app/INFO] Running ensureInstalledOnShop
/app/web/node_modules/@shopify/shopify-api/lib/error.js:13
var _this = _super.apply(this, tslib_1.__spreadArray([], tslib_1.__read(args), false)) || this;
^
```
InvalidRequestError: Request does not contain a host query parameter
at InvalidRequestError.ShopifyError [as constructor] (/app/web/node_modules/@shopify/shopify-api/lib/error.js:13:28)
at new InvalidRequestError (/app/web/node_modules/@shopify/shopify-api/lib/error.js:225:42)
at /app/web/node_modules/@shopify/shopify-api/lib/auth/get-embedded-app-url.js:28:31
at step (/app/web/node_modules/tslib/tslib.js:193:27)
at Object.next (/app/web/node_modules/tslib/tslib.js:174:57)
at fulfilled (/app/web/node_modules/tslib/tslib.js:164:62)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
my root package.son dependencies 

```
"dependencies": {
    "@shopify/app": "3.43.0",
    "@shopify/cli": "3.43.0",
    "shopify": "^0.1.0"
  },
```
route calling 

`https://{shopurl}.herokuapp.com/?shop={shopname}myshopify.com`

**Comment by jamalsoueidan** [comment]
Did you figure it out?

**Comment by mkevinosullivan** [comment]
To which hooks are you referring?

**Comment by jamalsoueidan** [comment]
useAppQuery or useAuthenticatedFetch

I think you mean when going to the app first time the host is added using the CLI right?

**Comment by mkevinosullivan** [comment]
What hooks are you using to call the API from the frontend?  Also, what version of App Bridge is being used?

**Comment by bashunaimiroy** [comment]
Hi, I'm a fellow dev working on a Shopify App, who's also experiencing this after creating an app from shopify-cli 3.45.1. 

I have a solution, even though I don't understand why it's necessary. The solution involves modifying the frontend code to add the parameter. I'm basing the solution on the React Frontend that the CLI creates- the source code is [here](https://github.com/Shopify/shopify-frontend-template-react/blob/main/hooks/useAuthenticatedFetch.js). It could be applied to other frontends, though.

I didn't have to remove the `ensureInstalledOnShop` middleware, although I completely understand why you did that, it's frustrating. 

Instead, I modified the `web/hooks/frontend/useAuthenticatedFetch.js` file, which contains a function called `useAuthenticatedFetch`. That function is (as the name suggests) meant to allow you to make authenticated fetch requests from the frontend to the backend. 

In that function, I added some code that will add the `host` parameter to the fetch request that goes out. Since it accepts a `uri` argument of type string, which is a relative URL, like "api/graphql" in my case, we can set the URL Params by doing some string manipulation to it. Here's the code I used:

```
function setUrlParams(url, key, value) {
  const urlSplit = url.split('?');
  const usp = new URLSearchParams(urlSplit[1]);
  usp.set(key, value);
  urlSplit[1] = usp.toString();
  return urlSplit.join('?');
}
```

and here's the new `useAuthenticatedFetch` function:

```
export function useAuthenticatedFetch() {
  const app = useAppBridge();
  const fetchFunction = authenticatedFetch(app);

  return async (uri, options) => {
    const currentHostValue = window.__SHOPIFY_DEV_HOST;
    const uriWithHostParam = setUrlParams(uri, 'host', currentHostValue);

    const response = await fetchFunction(uriWithHostParam, options);
    checkHeadersForReauthorization(response.headers, app);
    return response;
  };
}
```

Note that in my app, the `host` value is coming from a global variable: `window.__SHOPIFY_DEV_HOST`. this `window.__SHOPIFY_DEV_HOST` variable is set in [AppBridgeProvider.jsx](https://github.com/Shopify/shopify-frontend-template-react/blob/main/components/providers/AppBridgeProvider.jsx#L40-L42). If your app does not have this provider (e.g. because it's not embedded), you may have to get the `host` value from elsewhere in your app. Good luck. 

But as a side note, I have no idea why this is necessary.

**Comment by yaizudamashii** [comment]
Unfortunately neither of @bashunaimiroy 's solution worked for me.  

I have another theory.  When I console logged shop and host, host has a whitespace.  So maybe `ensureInstalledOnShop` is not able to handle whitespaces.  Why did the host have a whitespace in the first place?  I have no idea.

If you are developing a Shopify app, I'm sure that you are using a session storage.  Simply delete the entry that corresponds to your test shop, and Shopify will create a new host and session.  The new host did not have a whitespace, so the app under development ran fine for me after the deletion of the previous session.

**Comment by yaizudamashii** [comment]
Ok I spoke too soon, every subsequent request after generating a new session host fails and has a whitespace.  Something is happening but if you delete the session every time it works... obviously not a permanent solution.

**Comment by fidotheprince** [comment]
Okay here is the work around I found, 

When making a request on the frontend of your application to the backend, template the value for your host into the requested url. Below is an example via Shopify's authenticated fetch method. 

```js
  const fetch = useAuthenticatedFetch();

  //fetch data points data from API using the fetch function;
  const onSubmit = async () => {
    
    //host is added here to bypass shopify.ensureInstalledOnShop() in the backend;
    const host = `host=${window.__SHOPIFY_DEV_HOST}`
    const url = `/api/points?${host}`;
    const method = 'GET';

    const response = await fetch(url, { method, headers: { 'Content-Type': 'application/json' } });

    if (response.ok) {
      const data = await response.json();
      console.log(data);
    } 
  };
```

**Comment by dani-sanomads** [comment]
I have updated the shopify/cli and shopify/app to 3.47.2 and also updated the react-router-dom to 6.14.1 and it worked for me.
