### ISSUE TITLE
[Bug]: Unable to renew session 

### ISSUE THREAD

**Issue by pepicrft** [Shopify/shopify-app-template-node#900]
[Moved from this issue](https://github.com/Shopify/shopify-cli-next/issues/433)
Originally reported by @marvinhagemeister

### Please confirm that you have:

- [X] Searched [existing issues](https://github.com/Shopify/shopify-cli-next/issues) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://github.com/Shopify/shopify-cli-next/releases).

### What type of project are you working on?

App

### Expected behavior

I would have expected the CLI to automatically renew tokens.

### Actual behavior

Just came back to my machine after lunch and noticed that my app isn't showing up anymore. Instead I get a gateway timeout error:

```json
{"statusCode":504,"error":"Gateway Timeout","message":"Gateway Timeout"}
```

The error remains after refreshing the page. Checking the console it looks like the `jwt` token expired and the CLI doesn't seem to renew it.

### Stack trace

```shell
frontend   | 10:24:31 AM [vite] page reload pages/index.jsx
backend    | ERROR /Users/marvinhagemeister/src/test/shopify-beta/test-app/web/node_modules/@shopify/shopify-api/dist/error.js:13
backend    | ERROR         var _this = _super.apply(this, tslib_1.__spreadArray([], tslib_1.__read(args), false)) || this;
backend    | ERROR                            ^
backend    | ERROR 
backend    | ERROR InvalidJwtError: Failed to parse session token 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczpcL1wvbWFydmluLWhhZ2VtZWlzdGVyLWJldGEtc3RvcmUubXlzaG9waWZ5LmNvbVwvYWRtaW4iLCJkZXN0IjoiaHR0cHM6XC9cL21hcnZpbi1oYWdlbWVpc3Rlci1iZXRhLXN0b3JlLm15c2hvcGlmeS5jb20iLCJhdWQiOiI0ZDMwMmQ1ZjY5NWRlYmRjMzQxNGQ0YzRmYTc3YjUwOSIsInN1YiI6Ijc4ODc2MzQ0Mzc2IiwiZXhwIjoxNjU0MTYxNjM1LCJuYmYiOjE2NTQxNjE1NzUsImlhdCI6MTY1NDE2MTU3NSwianRpIjoiMjlkMDUzZWUtYWViMC00M2RmLWJhNzMtZDA5MDg4MmFlMTg2Iiwic2lkIjoiNWExZGM1YzYyZmZjODZhYmY5ZmE4N2VmMGM0ZTVkMzExOTRlZjFiNGIyYjBlMmRiYzExMjc4ZTM0NWNhNDMzYiJ9.wKeGN-gQrEIBjZrf10sVWGYuu-f35DUHVMro7Qzsz04': jwt expired
backend    | ERROR     at InvalidJwtError.ShopifyError [as constructor] (/Users/marvinhagemeister/src/test/shopify-beta/test-app/web/node_modules/@shopify/shopify-api/dist/error.js:13:28)
backend    | ERROR     at new InvalidJwtError (/Users/marvinhagemeister/src/test/shopify-beta/test-app/web/node_modules/@shopify/shopify-api/dist/error.js:39:42)
backend    | ERROR     at decodeSessionToken (/Users/marvinhagemeister/src/test/shopify-beta/test-app/web/node_modules/@shopify/shopify-api/dist/utils/decode-session-token.js:23:15)
backend    | ERROR     at Object.getCurrentSessionId (/Users/marvinhagemeister/src/test/shopify-beta/test-app/web/node_modules/@shopify/shopify-api/dist/auth/oauth/oauth.js:211:69)
backend    | ERROR     at Object.<anonymous> (/Users/marvinhagemeister/src/test/shopify-beta/test-app/web/node_modules/@shopify/shopify-api/dist/utils/load-current-session.js:19:46)
backend    | ERROR     at step (/Users/marvinhagemeister/src/test/shopify-beta/test-app/web/node_modules/tslib/tslib.js:144:27)
backend    | ERROR     at Object.next (/Users/marvinhagemeister/src/test/shopify-beta/test-app/web/node_modules/tslib/tslib.js:125:57)
backend    | ERROR     at /Users/marvinhagemeister/src/test/shopify-beta/test-app/web/node_modules/tslib/tslib.js:118:75
backend    | ERROR     at new Promise (<anonymous>)
backend    | ERROR     at Object.__awaiter (/Users/marvinhagemeister/src/test/shopify-beta/test-app/web/node_modules/tslib/tslib.js:114:16)
backend    | ERROR 
backend    | ERROR Node.js v18.2.0
frontend   | ERROR 12:05:45 PM [vite] http proxy error:
frontend   | ERROR Error: read ECONNRESET
frontend   | ERROR     at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
frontend   | ERROR 12:05:45 PM [vite] http proxy error:
frontend   | ERROR Error: socket hang up
frontend   | ERROR     at connResetException (node:internal/errors:693:14)
frontend   | ERROR     at Socket.socketOnEnd (node:_http_client:478:23)
frontend   | ERROR     at Socket.emit (node:events:539:35)
frontend   | ERROR     at endReadableNT (node:internal/streams/readable:1344:12)
frontend   | ERROR     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
backend    | [nodemon] app crashed - waiting for file changes before starting...
frontend   | ERROR 12:15:50 PM [vite] http proxy error:
frontend   | ERROR Error: connect ECONNREFUSED 127.0.0.1:56160
frontend   | ERROR     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1195:16)
frontend   | ERROR 12:17:12 PM [vite] http proxy error:
frontend   | ERROR Error: connect ECONNREFUSED 127.0.0.1:56160
frontend   | ERROR     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1195:16)
```

### Reproduction steps

1. Create an app and register that in the store
2. Wait until `jwt` is expired (not sure how long, was away for a bit more than an hour)

### Operating System

macOS Monterey

### Shopify CLI version (run `shopify version` if you're not sure)

3.0.4

### Shell

zsh

**Comment by bigjjjim** [comment]
> Hey @shafi-shaikat, we introduced session-management improvements in 3.0.25, do you mind updating the versions of `@shopify/cli` and `@shopify/app` in your project and trying again? If it keeps failing, could you invoke the CLI with `--verbose` and share the logs with me hiding any sensitive information from them?

Here is the bug happening with the verbose. I am in Indonesia at the moment, and the error seems to happen a lot more since i am here but it was already happening when I was in Portugal. 

```npm run dev --verbose
npm verb cli C:\Program Files\nodejs\node.exe C:\Users\jereh\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
npm info using npm@8.14.0
npm info using node@v16.14.0
npm timing npm:load:whichnode Completed in 0ms
npm timing config:load:defaults Completed in 1ms
npm timing config:load:file:C:\Users\jereh\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 3ms
npm timing config:load:builtin Completed in 3ms
npm timing config:load:cli Completed in 1ms
npm timing config:load:env Completed in 1ms
npm timing config:load:file:C:\Users\jereh\Documents\shopifyApps\internal-seo\.npmrc Completed in 1ms
npm timing config:load:project Completed in 3ms
npm timing config:load:file:C:\Users\jereh\.npmrc Completed in 0ms
npm timing config:load:user Completed in 0ms
npm timing config:load:file:C:\Users\jereh\AppData\Roaming\npm\etc\npmrc Completed in 0ms
npm timing config:load:global Completed in 1ms
npm timing config:load:validate Completed in 0ms
npm timing config:load:credentials Completed in 0ms
npm timing config:load:setEnvs Completed in 1ms
npm timing config:load Completed in 11ms
npm timing npm:load:configload Completed in 11ms
npm timing npm:load:mkdirpcache Completed in 1ms
npm timing npm:load:mkdirplogs Completed in 0ms
npm verb title npm run dev
npm verb argv "run" "dev" "--loglevel" "verbose"
npm timing npm:load:setTitle Completed in 1ms
npm timing config:load:flatten Completed in 2ms
npm timing npm:load:display Completed in 13ms
npm verb logfile logs-max:10 dir:C:\Users\jereh\AppData\Local\npm-cache\_logs
npm verb logfile C:\Users\jereh\AppData\Local\npm-cache\_logs\2022-09-18T06_31_30_992Z-debug-0.log
npm timing npm:load:logFile Completed in 16ms
npm timing npm:load:timers Completed in 0ms
npm timing npm:load:configScope Completed in 0ms
npm timing npm:load Completed in 43ms

> internal-seo@1.0.0 dev
> shopify app dev

✔ Dependencies installed
[..................] \ : timing npm:load Completed in 43ms
Using your previous dev settings:
- Org:          HBrothers
- App:          internal-seo
- Dev store:    hello-shop2.myshopify.com
- Update URLs:  Always

To reset your default dev config, run npm run dev -- --reset

✅ Success! The tunnel is running and you can now view your app.
✔ URL updated......] \ : timing npm:load Completed in 43ms


Shareable app URL

  https://edfe-202-57-4-210.ngrok.io?shop=hello-shop2.myshopify.com&host=aGVsbG8tc2hvcDIubXlzaG9waWZ5LmNvbS9hZG1pbg

frontend | npm.....] \ : timing npm:load Completed in 43ms
frontend |  verb cli [
frontend | npm verb cli   'C:\\Program Files\\nodejs\\node.exe',
frontend | npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
frontend | npm verb cli   'prefix',
frontend | npm verb cli   '-g'
frontend | npm verb cli ]
frontend | npm info using npm@8.3.1
frontend | npm info using node@v16.14.0
frontend | npm timing npm:load:whichnode Completed in 1ms
frontend | npm timing config:load:defaults Completed in 1ms
frontend | npm timing config:load:file:C:\Program Files\nodejs\node_modules\npm\npmrc Completed in 2ms
frontend | npm timing config:load:builtin Completed in 3ms
frontend | npm timing config:load:cli Completed in 1ms
frontend | npm timing config:load:env Completed in 2ms
frontend | npm timing config:load:project Completed in 2ms
frontend | npm timing config:load:file:C:\Users\jereh\.npmrc Completed in 1ms
frontend | npm timing config:load:user Completed in 1ms
frontend | npm timing config:load:file:C:\Users\jereh\AppData\Roaming\npm\etc\npmrc Completed in 0ms
frontend | npm timing config:load:global Completed in 0ms
frontend | npm timing config:load:validate Completed in 1ms
frontend | npm timing config:load:credentials Completed in 0ms
frontend | npm timing config:load:setEnvs Completed in 1ms
frontend | npm timing config:load Completed in 12ms
frontend | npm timing npm:load:configload Completed in 12ms
frontend | npm timing npm:load:setTitle Completed in 0ms
frontend | npm timing config:load:flatten Completed in 2ms
frontend | npm timing npm:load:display Completed in 4ms
frontend | npm verb logfile C:\Users\jereh\AppData\Local\npm-cache\_logs\2022-09-18T06_31_43_057Z-debug-0.log
frontend | npm timing npm:load:logFile Completed in 18ms
frontend | npm timing npm:load:timers Completed in 0ms
frontend | npm timing npm:load:configScope Completed in 0ms
frontend | npm timing npm:load Completed in 36ms
backend  | npm
backend  |  verb cli [
backend  | npm verb cli   'C:\\Program Files\\nodejs\\node.exe',
backend  | npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
backend  | npm verb 
backend  | cli   'prefix',
backend  | npm verb cli   '-g'
backend  | npm verb cli ]
backend  | npm
backend  |  info using npm@8.3.1
backend  | npm info using node@v16.14.0
backend  | npm timing npm:load:whichnode Completed in 0ms
backend  | npm timing config:load:defaults Completed in 2ms
backend  | npm timing config:load:file:C:\Program Files\nodejs\node_modules\npm\npmrc Completed in 4ms
backend  | npm timing config:load:builtin Completed in 4ms
backend  | npm timing config:load:cli Completed in 2ms
backend  | npm timing config:load:env Completed in 1ms
backend  | npm timing config:load:project Completed in 2ms
backend  | npm timing config:load:file:C:\Users\jereh\.npmrc Completed in 1ms
backend  | npm
backend  |  timing config:load:user Completed in 1ms
backend  | npm timing config:load:file:C:\Users\jereh\AppData\Roaming\npm\etc\npmrc Completed in 0ms
backend  | npm timing config:load:global Completed in 0ms
backend  | npm timing config:load:validate Completed in 1ms
backend  | npm timing config:load:credentials Completed in 1ms
backend  | npm timing config:load:setEnvs Completed in 1ms
backend  | npm timing config:load Completed in 16ms
backend  | npm timing npm:load:configload Completed in 16ms
backend  | npm timing npm:load:setTitle Completed in 1ms
backend  | npm timing config:load:flatten Completed in 4ms
backend  | npm timing
backend  |  npm:load:display
backend  |  Completed in 9ms
frontend | npm
frontend |  
frontend | timing
frontend |  
frontend | command:prefix Completed in 9ms
frontend | npm
frontend |  
frontend | verb
frontend |  
frontend | exit 0
frontend | npm
backend  | npm
backend  |  verb logfile C:\Users\jereh\AppData\Local\npm-cache\_logs\2022-09-18T06_31_43_076Z-debug-0.log
backend  | npm timing npm:load:logFile Completed in 8ms
backend  | npm timing npm:load:timers Completed in 0ms
backend  | npm timing npm:load:configScope Completed in 0ms
backend  | npm timing npm:load Completed in 39ms
frontend |  
frontend | timing npm Completed in 231ms
frontend | npm info
frontend |  ok 
backend  | npm timing command:prefix Completed in 1ms 43ms
backend  | npm verb exit 0
backend  | npm timing
backend  |  npm Completed in 226ms
backend  | npm info ok 
frontend | npm.....] \ : timing npm:load Completed in 43ms
backend  | npm
frontend |  verb cli C:\Program Files\nodejs\node.exe C:\Users\jereh\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
frontend | npm info using npm@8.14.0
frontend | npm info using node@v16.14.0
frontend | npm timing npm:load:whichnode Completed in 0ms
frontend | npm timing config:load:defaults Completed in 1ms
frontend | npm timing config:load:file:C:\Users\jereh\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 1ms
frontend | npm timing config:load:builtin Completed in 2ms
frontend | npm timing config:load:cli Completed in 1ms
frontend | npm timing config:load:env Completed in 1ms
frontend | npm timing config:load:file:C:\Users\jereh\Documents\shopifyApps\internal-seo\web\frontend\.npmrc Completed in 0ms
frontend | npm timing config:load:project Completed in 3ms
frontend | npm timing config:load:file:C:\Users\jereh\.npmrc Completed in 0ms
frontend | npm timing config:load:user Completed in 1ms
frontend | npm timing config:load:file:C:\Users\jereh\AppData\Roaming\npm\etc\npmrc Completed in 0ms
frontend | npm timing config:load:global Completed in 0ms
frontend | npm timing
backend  |  verb cli C:\Program Files\nodejs\node.exe C:\Users\jereh\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
backend  | npm info using npm@8.14.0
backend  | npm info using node@v16.14.0
backend  | npm timing npm:load:whichnode Completed in 0ms
backend  | npm timing config:load:defaults Completed in 1ms
backend  | npm timing config:load:file:C:\Users\jereh\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 1ms
backend  | npm timing config:load:builtin Completed in 1ms
backend  | npm timing config:load:cli Completed in 1ms
backend  | npm timing config:load:env Completed in 1ms
backend  | npm timing config:load:file:C:\Users\jereh\Documents\shopifyApps\internal-seo\web\.npmrc Completed in 0ms
backend  | npm timing config:load:project Completed in 2ms
backend  | npm timing config:load:file:C:\Users\jereh\.npmrc Completed in 1ms
backend  | npm timing config:load:user Completed in 1ms
backend  | npm timing config:load:file:C:\Users\jereh\AppData\Roaming\npm\etc\npmrc Completed in 0ms
backend  | npm timing config:load:global Completed in 0ms
backend  | npm timing config:load:validate Completed in 0ms
backend  | npm timing config:load:credentials Completed in 1ms
backend  | npm timing config:load:setEnvs Completed in 0ms
backend  | npm timing config:load Completed in 9ms
backend  | npm timing npm:load:configload Completed in 10ms
backend  | npm timing npm:load:mkdirpcache Completed in 0ms
backend  | npm timing npm:load:mkdirplogs Completed in 0ms
backend  | npm verb title npm run dev
backend  | npm verb argv "run" "dev"
backend  | npm timing npm:load:setTitle Completed in 1ms
backend  | npm timing config:load:flatten Completed in 2ms
backend  | npm timing npm:load:display Completed in 4ms
backend  | npm verb logfile logs-max:10 dir:C:\Users\jereh\AppData\Local\npm-cache\_logs
frontend |  config:load:validate Completed in 0ms
frontend | npm timing config:load:credentials Completed in 1ms
frontend | npm timing config:load:setEnvs Completed in 0ms
frontend | npm timing config:load Completed in 10ms
frontend | npm timing npm:load:configload Completed in 10ms
frontend | npm timing npm:load:mkdirpcache Completed in 1ms
frontend | npm timing npm:load:mkdirplogs Completed in 0ms
frontend | npm verb title npm run dev
frontend | npm verb argv "run" "dev"
frontend | npm timing npm:load:setTitle Completed in 1ms
frontend | npm timing config:load:flatten Completed in 2ms
frontend | npm timing npm:load:display Completed in 3ms
frontend | npm verb logfile logs-max:10 dir:C:\Users\jereh\AppData\Local\npm-cache\_logs
frontend | npm verb logfile C:\Users\jereh\AppData\Local\npm-cache\_logs\2022-09-18T06_31_43_687Z-debug-0.log
frontend | npm timing npm:load:logFile Completed in 6ms
frontend | npm timing npm:load:timers Completed in 0ms
backend  | npm verb logfile C:\Users\jereh\AppData\Local\npm-cache\_logs\2022-09-18T06_31_43_688Z-debug-0.log
backend  | npm timing npm:load:logFile Completed in 5ms
backend  | npm timing npm:load:timers Completed in 0ms
backend  | npm timing npm:load:configScope Completed in 0ms
backend  | npm timing npm:load Completed in 21ms
frontend | npm timing npm:load:configScope Completed in 0ms
frontend | npm timing npm:load Completed in 25ms
backend  | 
backend  | > dev
backend  | > cross-env NODE_ENV=development nodemon index.js --ignore ./frontend
backend  | 
frontend | 
frontend | > dev
frontend | > vite
frontend | 
backend  | [nodemon] 2.0.19ming npm:load Completed in 43ms
backend  | [nodemon] to restart at any time, enter `rs`
backend  | [nodemon] watching path(s): *.*
backend  | [nodemon] watching extensions: js,mjs,json
backend  | [nodemon] starting `node index.js`
frontend | ........] \ : timing npm:load Completed in 43ms
frontend |   vite v2.9.14 dev server running at:
frontend |
frontend |   > Network:  http://192.168.0.102:58124/
frontend |   > Local:    http://localhost:58124/
frontend |
frontend |   ready in 307ms.
frontend |
backend  | C:\Users\jereh\Documents\shopifyApps\internal-seo\web\node_modules\@shopify\shopify-api\dist\error.js:13
backend  |         var _this = _super.apply(this, tslib_1.__spreadArray([], tslib_1.__read(args), false)) || this;
backend  |                            ^
backend  | 
backend  | InvalidJwtError: Failed to parse session token 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczpcL1wvaGVsbG8tc2hvcDIubXlzaG9waWZ5LmNvbVwvYWRtaW4iLCJkZXN0IjoiaHR0cHM6XC9cL2hlbGxvLXNob3AyLm15c2hvcGlmeS5jb20iLCJhdWQiOiI3YzA4YTZmZWQ4NTcwOGViZDFiYTllMjkwNzgzNWE1MCIsInN1YiI6IjcwNTAyOTQwODMyIiwiZXhwIjoxNjYzNDgyODQwLCJuYmYiOjE2NjM0ODI3ODAsImlhdCI6MTY2MzQ4Mjc4MCwianRpIjoiMWRhZTljZDktNDc4Yi00ODdkLWI2ZGItY2ZlMDEyN2M3ODZmIiwic2lkIjoiN2MzZjIxMzcyOTE4YWQ1YTQ1MTEzNGQ5YjA0MGZjNmQ0ZTc4NDQyYWYxYjRiYjBmYmMxNTI1MjQxYjQ2YzQ0MiJ9.dr6ZeUVV7erq_d9WNdVk-0k8TUApi9lPoHdQyLkFWEA': jwt not active
backend  |     at InvalidJwtError.ShopifyError [as constructor] (C:\Users\jereh\Documents\shopifyApps\internal-seo\web\node_modules\@shopify\shopify-api\dist\error.js:13:28)
backend  |     at new InvalidJwtError (C:\Users\jereh\Documents\shopifyApps\internal-seo\web\node_modules\@shopify\shopify-api\dist\error.js:47:42)
backend  |     at decodeSessionToken (C:\Users\jereh\Documents\shopifyApps\internal-seo\web\node_modules\@shopify\shopify-api\dist\utils\decode-session-token.js:23:15)
backend  |     at Object.getCurrentSessionId (C:\Users\jereh\Documents\shopifyApps\internal-seo\web\node_modules\@shopify\shopify-api\dist\auth\oauth\oauth.js:213:69)
backend  |     at Object.<anonymous> (C:\Users\jereh\Documents\shopifyApps\internal-seo\web\node_modules\@shopify\shopify-api\dist\utils\load-current-session.js:19:46)
backend  |     at step (C:\Users\jereh\Documents\shopifyApps\internal-seo\web\node_modules\tslib\tslib.js:144:27)
backend  |     at Object.next (C:\Users\jereh\Documents\shopifyApps\internal-seo\web\node_modules\tslib\tslib.js:125:57)
backend  |     at C:\Users\jereh\Documents\shopifyApps\internal-seo\web\node_modules\tslib\tslib.js:118:75
backend  |     at new Promise (<anonymous>)
backend  |     at Object.__awaiter (C:\Users\jereh\Documents\shopifyApps\internal-seo\web\node_modules\tslib\tslib.js:114:16)
backend  | [nodemon] app crashed - waiting for file changes before starting...
frontend | 1:32:52 PM [vite] http proxy error:
frontend | Error: read ECONNRESET
frontend |     at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
✔ Dependencies installed timing npm:load Completed in 43ms```

**Comment by bigjjjim** [comment]
This is still an issue. Even simply creating the example app with 

`npm init @shopify/app@latest`

and still get this error very often when running it. I seems like it is related to the speed of connection to Shopifys servers. 

Can someone from Shopify team at least let us know what is going on and if there are plans to fix the issue? 

@pepicrft

**Comment by bigjjjim** [comment]
I believe this thread is about the same issue: 

https://github.com/Shopify/shopify-api-node/issues/207

And fixing my settings on time and time zone to the automatic option seems to have fixed the issue as of now!!

**Comment by vishnu-acodez** [comment]
hii any update on this issue?

**Comment by vishnu-acodez** [comment]
> pepicrft
hii any update on this issue?
