### ISSUE TITLE
Heroku Questions

### ISSUE THREAD

**Issue by wfrohwein** [Shopify/shopify-app-template-node#975]
# Issue summary

I have some questions regarding Heroku setup for a Shopify app using node.js. Do you need to use a Procfile and or Buildpack with Heroku? 

## Steps to reproduce the problem

All this was done today Friday July 29th 2022

1. Created a new github repo
2. Created a new shopify app using yarn create @shopify/app
3. Started the app using yarn dev
4. This put it in my shopify dev account.
5. Installed the app in my dev store. You can see it just fine.
6. Created a new heroku app using the node.js buildpack
7. Connected heroku to my github account and selected the correct repo with auto deploy enabled.
8. Connected my shopify app project folder to git by adding the remote.
9. Pushed up an initial commit. This kicked off the auto deploy to heroku.

This is the errors i see when tailing the heroku logs:

```
Starting process with command `npm start`
npm ERR! Missing script: "start"
npm ERR! A complete log of this run can be found in:
npm ERR!     /app/.npm/_logs/2022-07-29T21_49_59_555Z-debug-0.log
```

The process crashes and does the same logging output as above again. The log file it generated has this inside:

```
36 verbose stack Error: Missing script: "build"
36 verbose stack
36 verbose stack To see a list of scripts, run:
36 verbose stack   npm run
36 verbose stack     at RunScript.run (/usr/local/lib/node_modules/npm/lib/commands/run-script.js:98:13)
36 verbose stack     at async module.exports (/usr/local/lib/node_modules/npm/lib/cli.js:78:5)
37 verbose cwd /Users/wfrohwein/Documents/heroku-test/web
38 verbose Darwin 21.5.0
39 verbose node v18.6.0
40 verbose npm  v8.13.2
41 error Missing script: "build"
41 error
41 error To see a list of scripts, run:
41 error   npm run
42 verbose exit 1
```

Which is basically the same above.

So i look in the project root package.json file and sure enough, i do not see a start command. I only see these:

```
  "scripts": {
    "shopify": "shopify",
    "build": "shopify app build",
    "dev": "shopify app dev",
    "info": "shopify app info",
    "scaffold": "shopify app scaffold",
    "deploy": "shopify app deploy"
  },
```

So i created a Procfile with the contents:
```
web: npm run dev
```

But then i get an error about "process.stdin.setRawMode is not a function"

```
2022-07-29T22:10:46.312204+00:00 heroku[web.1]: Starting process with command `npm run dev`
2022-07-29T22:10:48.072497+00:00 app[web.1]: 
2022-07-29T22:10:48.072510+00:00 app[web.1]: > heroku-test2@1.0.0 dev
2022-07-29T22:10:48.072511+00:00 app[web.1]: > shopify app dev
2022-07-29T22:10:48.072511+00:00 app[web.1]: 
2022-07-29T22:10:49.932146+00:00 app[web.1]: [STARTED] Installing any necessary dependencies
2022-07-29T22:10:54.051726+00:00 app[web.1]: [TITLE] Dependencies installed
2022-07-29T22:10:54.052043+00:00 app[web.1]: [SUCCESS] Dependencies installed
2022-07-29T22:10:54.059044+00:00 app[web.1]: 
2022-07-29T22:10:54.059046+00:00 app[web.1]: To run this command, log in to Shopify Partners.
2022-07-29T22:10:54.059200+00:00 app[web.1]: 👉 Press any key to open the login page on your browser
2022-07-29T22:10:54.090231+00:00 app[web.1]: 
2022-07-29T22:10:54.090237+00:00 app[web.1]: ━━━━━━ Error ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-07-29T22:10:54.090238+00:00 app[web.1]: process.stdin.setRawMode is not a function
2022-07-29T22:10:54.090238+00:00 app[web.1]: 
2022-07-29T22:10:54.090239+00:00 app[web.1]: Stack trace:
2022-07-29T22:10:54.090240+00:00 app[web.1]: at keypress                   @shopify/cli-kit/src/ui.ts:186                process.stdin.setRawMode(true)
2022-07-29T22:10:54.090240+00:00 app[web.1]: at authorize                  @shopify/cli-kit/src/session/authorize.ts:44  await keypress()
2022-07-29T22:10:54.090240+00:00 app[web.1]: at async executeCompleteFlo…  @shopify/cli-kit/src/session.ts:268           const code = await authorize(scopes)
2022-07-29T22:10:54.090240+00:00 app[web.1]: at async ensureAuthenticate…  @shopify/cli-kit/src/session.ts:180           newSession = await executeCompleteFlow(applications, fqdn)
2022-07-29T22:10:54.090241+00:00 app[web.1]: at ensureAuthenticatedPartn…  @shopify/cli-kit/src/session.ts:111           const tokens = await ensureAuthenticated({partnersApi: {scopes}})
2022-07-29T22:10:54.090241+00:00 app[web.1]: at async dev                  @shopify/app/src/cli/services/dev.ts:47       const token = await session.ensureAuthenticatedPartners()
2022-07-29T22:10:54.090241+00:00 app[web.1]: at run                        @shopify/app/src/cli/commands/app/dev.ts:81   await dev({
2022-07-29T22:10:54.090241+00:00 app[web.1]: 
2022-07-29T22:10:54.090242+00:00 app[web.1]: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2022-07-29T22:10:54.090242+00:00 app[web.1]: 
2022-07-29T22:10:54.533176+00:00 heroku[web.1]: State changed from starting to crashed
```

I figured this is because it was expecting me to run that command from my local computer via command line. Which also makes me think, this is the wrong command for heroku. But none of the other commands above sound like the command that starts the app.

Now inside the web folder, that package.json has the following commands:

```
  "scripts": {
    "debug": "node --inspect-brk index.js",
    "dev": "cross-env NODE_ENV=development nodemon index.js --ignore ./frontend",
    "serve": "cross-env NODE_ENV=production node index.js"
  },
```

Now these sound more accurate to execute. But how do i run them from the parent folder? Maybe just upload the web folder to heroku instead of the entire project? So i did that and had this in my Procfile:

```
web: npm run dev
```

and got this

```
2022-07-29T22:29:59.870328+00:00 heroku[web.1]: State changed from crashed to starting
2022-07-29T22:30:02.820051+00:00 heroku[web.1]: Starting process with command `npm run dev`
2022-07-29T22:30:03.812827+00:00 app[web.1]: 
2022-07-29T22:30:03.812842+00:00 app[web.1]: > dev
2022-07-29T22:30:03.812842+00:00 app[web.1]: > cross-env NODE_ENV=development nodemon index.js --ignore ./frontend
2022-07-29T22:30:03.812842+00:00 app[web.1]: 
2022-07-29T22:30:03.989135+00:00 app[web.1]: [nodemon] 2.0.19
2022-07-29T22:30:03.989413+00:00 app[web.1]: [nodemon] to restart at any time, enter `rs`
2022-07-29T22:30:03.989835+00:00 app[web.1]: [nodemon] watching path(s): *.*
2022-07-29T22:30:03.989887+00:00 app[web.1]: [nodemon] watching extensions: js,mjs,json
2022-07-29T22:30:03.990309+00:00 app[web.1]: [nodemon] starting `node index.js`
2022-07-29T22:30:05.002076+00:00 heroku[web.1]: State changed from starting to up
```

So now its up and running. So i go to the app in my dev login. Add it to one of my dev stores, you get the message about allow access of the app to your dev store. Then it white screens at a url like this:

https://someapp.herokuapp.com/?shop=mydevstorename.myshopify.com&host=bunchofcharacthershere

Logs show this now

```
2022-07-29T22:34:37.534338+00:00 heroku[router]: at=info method=GET path="/api/auth?shop=commission-tracker-dev.myshopify.com" host=shopify-heroku-test.herokuapp.com request_id=72914328-a5df-4825-88c9-66298973befa fwd="68.227.235.45" dyno=web.1 connect=0ms service=2ms status=302 bytes=412 protocol=https
2022-07-29T22:34:37.452036+00:00 heroku[router]: at=info method=GET path="/?hmac=ea92b76bcddbf8253fef9971194fcf8a0cf945eabff9fef7fd458682a22b84d2&host=Y29tbWlzc2lvbi10cmFja2VyLWRldi5teXNob3BpZnkuY29tL2FkbWlu&shop=commission-tracker-dev.myshopify.com&timestamp=1659134077" host=shopify-heroku-test.herokuapp.com request_id=3c858552-f459-4b4f-ba8f-065a2518e1c2 fwd="68.227.235.45" dyno=web.1 connect=1ms service=4ms status=302 bytes=499 protocol=https
2022-07-29T22:34:37.741691+00:00 heroku[router]: at=info method=GET path="/api/auth/toplevel?shop=commission-tracker-dev.myshopify.com" host=shopify-heroku-test.herokuapp.com request_id=3d933653-4f6e-49fe-8106-8b281cc53cfe fwd="68.227.235.45" dyno=web.1 connect=0ms service=2ms status=200 bytes=1430 protocol=https
2022-07-29T22:34:37.924067+00:00 heroku[router]: at=info method=GET path="/api/auth?shop=commission-tracker-dev.myshopify.com" host=shopify-heroku-test.herokuapp.com request_id=6211998b-cf44-4ab8-8a1d-58cfc903a5d5 fwd="68.227.235.45" dyno=web.1 connect=0ms service=6ms status=302 bytes=1444 protocol=https
2022-07-29T22:34:45.984271+00:00 heroku[router]: at=info method=GET path="/api/auth/callback?code=f5351f59901db9f152a925b1c77c697b&hmac=a31e68a82d5e7bdedc7faaa884d9bb9424a694841533bd773dd0303c4316a229&host=Y29tbWlzc2lvbi10cmFja2VyLWRldi5teXNob3BpZnkuY29tL2FkbWlu&shop=commission-tracker-dev.myshopify.com&state=505802115622416&timestamp=1659134084" host=shopify-heroku-test.herokuapp.com request_id=0a379cd7-1304-4be8-8e76-b5c40082e030 fwd="68.227.235.45" dyno=web.1 connect=0ms service=908ms status=302 bytes=856 protocol=https
2022-07-29T22:34:46.322450+00:00 heroku[router]: at=info method=GET path="/index.jsx" host=shopify-heroku-test.herokuapp.com request_id=4d157a3c-8f08-41ad-b3bf-277b0b751817 fwd="68.227.235.45" dyno=web.1 connect=0ms service=2ms status=304 bytes=200 protocol=https
2022-07-29T22:34:46.417398+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=shopify-heroku-test.herokuapp.com request_id=545c9164-a907-455e-8e50-f61f7f1689cc fwd="68.227.235.45" dyno=web.1 connect=0ms service=2ms status=304 bytes=200 protocol=https
2022-07-29T22:34:46.224808+00:00 heroku[router]: at=info method=GET path="/?shop=commission-tracker-dev.myshopify.com&host=Y29tbWlzc2lvbi10cmFja2VyLWRldi5teXNob3BpZnkuY29tL2FkbWlu" host=shopify-heroku-test.herokuapp.com request_id=347d71fc-e8f0-4fc9-b87a-fd4586b28ff7 fwd="68.227.235.45" dyno=web.1 connect=0ms service=2ms status=304 bytes=264 protocol=https
```

Even though it white screens, the app still installed as i can see it in my dev store. If i click on it, you only see the name of that app in the header, then where the app is supposed to show, is all blank.

It shows this in the logs:

```
2022-07-29T22:39:23.254222+00:00 heroku[router]: at=info method=GET path="/?hmac=bunchofletersandnumbers&host=bunchofletersandnumbers&locale=en-US&session=bunchofletersandnumbers&shop=myshopname.myshopify.com&timestamp=1659134362" host=myherokuapp.herokuapp.com request_id=bunchofletersandnumbers fwd="some_ip_address" dyno=web.1 connect=0ms service=2ms status=200 bytes=538 protocol=https
2022-07-29T22:39:23.490470+00:00 heroku[router]: at=info method=GET path="/index.jsx" host=myherokuapp.herokuapp.com request_id=bunchofletersandnumbers fwd="some_ip_address" dyno=web.1 connect=0ms service=1ms status=200 bytes=474 protocol=https
```

So i notice inside the web/frontend folder, there is ANOTHER package.json file that has this for commands:

```
  "scripts": {
    "build": "vite build",
    "dev": "vite",
    "test": "vitest",
    "coverage": "vitest run --coverage"
  },
```

So i am just really lost as to which package.json is main one for running the shopify app on heroku. There is a couple tutorials out there on how to create a shopify app and push it to heroku, but none of them worked for me. I feel they are outdated.

## Specifications

Versions from my mac:

wfrohwein@MBP web % shopify version 2.20.1
wfrohwein@MBP web % yarn --version 1.22.19
wfrohwein@MBP web % npm --version 8.13.2
wfrohwein@MBP web % node --version v18.6.0

I have included the 3 package.json files. This is a new app. I have not even modified any of the pages or added new pages or functionality.

[root_package.json.txt](https://github.com/Shopify/shopify-app-template-node/files/9223729/root_package.json.txt)
[web_package.json.txt](https://github.com/Shopify/shopify-app-template-node/files/9223731/web_package.json.txt)
[frontend_package.json.txt](https://github.com/Shopify/shopify-app-template-node/files/9223733/frontend_package.json.txt)

Thank you all for any help you can provide me.

**Comment by zvndev** [comment]
@wfrohwein - Could you share some examples from your successful deploy?  Your above example is spot on exactly what I'm experiencing currently.
I'm curious what you mean by `converted the heroku stack to a container`.

Thanks so much for your time.

**Comment by topBEdev** [comment]
> h

Can you share your heroku.yml file template? I get deploy success message but if I open app, I get "Application Error".
Thanks.

**Comment by umang135** [comment]
Any update on this? thanks

**Comment by wfrohwein** [comment]
> @wfrohwein - Could you share some examples from your successful deploy? Your above example is spot on exactly what I'm experiencing currently. I'm curious what you mean by `converted the heroku stack to a container`.
> 
> Thanks so much for your time.

Hey sorry for the late reply. I ended up using docker and it my file looks like the one you just recently posted. There is so much thats not documented. I gave up for a while building the plugins. I will come back to it soon when they have real working examples on their site.

**Comment by gordonchanhk** [comment]
I encounter this and I believe you are using an existing Heroku app with other stack (web / nodoejs).
After reading https://devcenter.heroku.com/articles/build-docker-images-heroku-yml
I find this command: `heroku stack:set container` is indeed for such stack conversion.
It needs to follow with a git push / deploy to get the change effective.
